<?xml version="1.0" encoding="utf-8"?><Database Name="QL_CUAHANG3" Class="QLCHDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-3R4ARS4\HA;Initial Catalog=QL_CUAHANG3;Integrated Security=True" SettingsObjectName="BLL_DAL.Properties.Settings" SettingsPropertyName="QL_CUAHANG3ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CTHOADON" Member="CTHOADONs">
    <Type Name="CTHOADON">
      <Column Name="MACTHD" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHD" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_CTHOADON" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="HOADON_CTHOADON" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MASP" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MALOAI" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="MANCC" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONVITINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_CTHOADON" Member="CTHOADONs" ThisKey="MASP" OtherKey="MASP" Type="CTHOADON" />
      <Association Name="SANPHAM_CTPHIEUNHAPHANG" Member="CTPHIEUNHAPHANGs" ThisKey="MASP" OtherKey="MASP" Type="CTPHIEUNHAPHANG" />
      <Association Name="LOAISP_SANPHAM" Member="LOAISP" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAISP" IsForeignKey="true" />
      <Association Name="NHACC_SANPHAM" Member="NHACC" ThisKey="MANCC" OtherKey="MANCC" Type="NHACC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTPHIEUNHAPHANG" Member="CTPHIEUNHAPHANGs">
    <Type Name="CTPHIEUNHAPHANG">
      <Column Name="MACTPHIEUNHAP" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAPHIEUNHAP" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONVITINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_CTPHIEUNHAPHANG" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="PHIEUNHAPHANG_CTPHIEUNHAPHANG" Member="PHIEUNHAPHANG" ThisKey="MAPHIEUNHAP" OtherKey="MAPHIEUNHAP" Type="PHIEUNHAPHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DM_ManHinh" Member="DM_ManHinhs">
    <Type Name="DM_ManHinh">
      <Column Name="MaManHinh" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenManHinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.dulieuTrans" Member="dulieuTrans">
    <Type Name="dulieuTran">
      <Column Name="MAHD" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MACTHD" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="MASP" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYDAT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CTHOADON" Member="CTHOADONs" ThisKey="MAHD" OtherKey="MAHD" Type="CTHOADON" />
      <Association Name="KHACHHANG_HOADON" Member="KHACHHANG" ThisKey="MAKH" OtherKey="MAKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NHANVIEN_HOADON" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MAKH" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KHACHHANG_HOADON" Member="HOADONs" ThisKey="MAKH" OtherKey="MAKH" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISP" Member="LOAISPs">
    <Type Name="LOAISP">
      <Column Name="MALOAI" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAISP_SANPHAM" Member="SANPHAMs" ThisKey="MALOAI" OtherKey="MALOAI" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.NHACC" Member="NHACCs">
    <Type Name="NHACC">
      <Column Name="MANCC" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHACC_SANPHAM" Member="SANPHAMs" ThisKey="MANCC" OtherKey="MANCC" Type="SANPHAM" />
      <Association Name="NHACC_PHIEUNHAPHANG" Member="PHIEUNHAPHANGs" ThisKey="MANCC" OtherKey="MANCC" Type="PHIEUNHAPHANG" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NHANVIEN_HOADON" Member="HOADONs" ThisKey="MANV" OtherKey="MANV" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUNHAPHANG" Member="PHIEUNHAPHANGs">
    <Type Name="PHIEUNHAPHANG">
      <Column Name="MAPHIEUNHAP" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANCC" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NGAYNHAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHIEUNHAPHANG_CTPHIEUNHAPHANG" Member="CTPHIEUNHAPHANGs" ThisKey="MAPHIEUNHAP" OtherKey="MAPHIEUNHAP" Type="CTPHIEUNHAPHANG" />
      <Association Name="NHACC_PHIEUNHAPHANG" Member="NHACC" ThisKey="MANCC" OtherKey="MANCC" Type="NHACC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NguoiDung" Member="QL_NguoiDungs">
    <Type Name="QL_NguoiDung">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HoatDong" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NguoiDungNhomNguoiDung" Member="QL_NguoiDungNhomNguoiDungs">
    <Type Name="QL_NguoiDungNhomNguoiDung">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhomNguoiDung" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NhomNguoiDung" Member="QL_NhomNguoiDungs">
    <Type Name="QL_NhomNguoiDung">
      <Column Name="MaNhom" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_PhanQuyen" Member="QL_PhanQuyens">
    <Type Name="QL_PhanQuyen">
      <Column Name="MaNhomNguoiDung" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaManHinh" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CoQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>